Add-BootsFunction -Type 'Microsoft.Win32.OpenFileDialog',
'Microsoft.Win32.SaveFileDialog',
'System.Windows.Annotations.Annotation',
'System.Windows.Annotations.AnnotationResource',
'System.Windows.Annotations.ContentLocator',
'System.Windows.Annotations.ContentLocatorGroup',
'System.Windows.Controls.Primitives.BulletDecorator',
'System.Windows.Controls.Primitives.DocumentPageView',
'System.Windows.Controls.Primitives.Popup',
'System.Windows.Controls.Primitives.RepeatButton',
'System.Windows.Controls.Primitives.ResizeGrip',
'System.Windows.Controls.Primitives.ScrollBar',
'System.Windows.Controls.Primitives.StatusBar',
'System.Windows.Controls.Primitives.StatusBarItem',
'System.Windows.Controls.Primitives.TabPanel',
'System.Windows.Controls.Primitives.Thumb',
'System.Windows.Controls.Primitives.TickBar',
'System.Windows.Controls.Primitives.ToggleButton',
'System.Windows.Controls.Primitives.ToolBarOverflowPanel',
'System.Windows.Controls.Primitives.ToolBarPanel',
'System.Windows.Controls.Primitives.Track',
'System.Windows.Controls.Primitives.UniformGrid',
'System.Windows.Controls.AccessText',
'System.Windows.Controls.AdornedElementPlaceholder',
'System.Windows.Controls.AlternationConverter',
'System.Windows.Controls.BooleanToVisibilityConverter',
'System.Windows.Controls.Border',
'System.Windows.Controls.BorderGapMaskConverter',
'System.Windows.Controls.Button',
'System.Windows.Controls.Canvas',
'System.Windows.Controls.CheckBox',
'System.Windows.Controls.ColumnDefinition',
'System.Windows.Controls.ComboBox',
'System.Windows.Controls.ComboBoxItem',
'System.Windows.Controls.ContentControl',
'System.Windows.Controls.ContentPresenter',
'System.Windows.Controls.ContextMenu',
'System.Windows.Controls.Control',
'System.Windows.Controls.ControlTemplate',
'System.Windows.Controls.DataErrorValidationRule',
'System.Windows.Controls.DataTemplateSelector',
'System.Windows.Controls.Decorator',
'System.Windows.Controls.DockPanel',
'System.Windows.Controls.DocumentViewer',
'System.Windows.Controls.ExceptionValidationRule',
'System.Windows.Controls.Expander',
'System.Windows.Controls.FlowDocumentPageViewer',
'System.Windows.Controls.FlowDocumentReader',
'System.Windows.Controls.FlowDocumentScrollViewer',
'System.Windows.Controls.Frame',
'System.Windows.Controls.Grid',
'System.Windows.Controls.GridSplitter',
'System.Windows.Controls.GridView',
'System.Windows.Controls.GridViewColumn',
'System.Windows.Controls.GridViewColumnCollection',
'System.Windows.Controls.GridViewColumnHeader',
'System.Windows.Controls.GridViewHeaderRowPresenter',
'System.Windows.Controls.GridViewRowPresenter',
'System.Windows.Controls.GroupBox',
'System.Windows.Controls.GroupItem',
'System.Windows.Controls.GroupStyle',
'System.Windows.Controls.HeaderedContentControl',
'System.Windows.Controls.HeaderedItemsControl',
'System.Windows.Controls.Image',
'System.Windows.Controls.InkCanvas',
'System.Windows.Controls.InkPresenter',
'System.Windows.Controls.ItemsControl',
'System.Windows.Controls.ItemsPanelTemplate',
'System.Windows.Controls.ItemsPresenter',
'System.Windows.Controls.Label',
'System.Windows.Controls.ListBox',
'System.Windows.Controls.ListBoxItem',
'System.Windows.Controls.ListView',
'System.Windows.Controls.ListViewItem',
'System.Windows.Controls.MediaElement',
'System.Windows.Controls.Menu',
'System.Windows.Controls.MenuItem',
'System.Windows.Controls.MenuScrollingVisibilityConverter',
'System.Windows.Controls.Page',
'System.Windows.Controls.PasswordBox',
'System.Windows.Controls.PrintDialog',
'System.Windows.Controls.PrintDialogException',
'System.Windows.Controls.ProgressBar',
'System.Windows.Controls.RadioButton',
'System.Windows.Controls.RichTextBox',
'System.Windows.Controls.RowDefinition',
'System.Windows.Controls.ScrollContentPresenter',
'System.Windows.Controls.ScrollViewer',
'System.Windows.Controls.Separator',
'System.Windows.Controls.Slider',
'System.Windows.Controls.SoundPlayerAction',
'System.Windows.Controls.StackPanel',
'System.Windows.Controls.StyleSelector',
'System.Windows.Controls.TabControl',
'System.Windows.Controls.TabItem',
'System.Windows.Controls.TextBlock',
'System.Windows.Controls.TextBox',
'System.Windows.Controls.ToolBar',
'System.Windows.Controls.ToolBarTray',
'System.Windows.Controls.ToolTip',
'System.Windows.Controls.TreeView',
'System.Windows.Controls.TreeViewItem',
'System.Windows.Controls.UserControl',
'System.Windows.Controls.Viewbox',
'System.Windows.Controls.Viewport3D',
'System.Windows.Controls.VirtualizingStackPanel',
'System.Windows.Controls.WebBrowser',
'System.Windows.Controls.WrapPanel',
'System.Windows.Data.Binding',
'System.Windows.Data.BindingGroup',
'System.Windows.Data.CollectionContainer',
'System.Windows.Data.CollectionViewSource',
'System.Windows.Data.CompositeCollection',
'System.Windows.Data.MultiBinding',
'System.Windows.Data.ObjectDataProvider',
'System.Windows.Data.PriorityBinding',
'System.Windows.Data.PropertyGroupDescription',
'System.Windows.Data.RelativeSource',
'System.Windows.Data.ValueUnavailableException',
'System.Windows.Data.XmlDataProvider',
'System.Windows.Data.XmlNamespaceMapping',
'System.Windows.Data.XmlNamespaceMappingCollection',
'System.Windows.Documents.DocumentStructures.BlockElement',
'System.Windows.Documents.DocumentStructures.FigureStructure',
'System.Windows.Documents.DocumentStructures.ListItemStructure',
'System.Windows.Documents.DocumentStructures.ListStructure',
'System.Windows.Documents.DocumentStructures.NamedElement',
'System.Windows.Documents.DocumentStructures.ParagraphStructure',
'System.Windows.Documents.DocumentStructures.SectionStructure',
'System.Windows.Documents.DocumentStructures.StoryBreak',
'System.Windows.Documents.DocumentStructures.StoryFragment',
'System.Windows.Documents.DocumentStructures.StoryFragments',
'System.Windows.Documents.DocumentStructures.TableCellStructure',
'System.Windows.Documents.DocumentStructures.TableRowGroupStructure',
'System.Windows.Documents.DocumentStructures.TableRowStructure',
'System.Windows.Documents.DocumentStructures.TableStructure',
'System.Windows.Documents.AdornerDecorator',
'System.Windows.Documents.BlockUIContainer',
'System.Windows.Documents.Bold',
'System.Windows.Documents.DocumentReference',
'System.Windows.Documents.Figure',
'System.Windows.Documents.FixedDocument',
'System.Windows.Documents.FixedDocumentSequence',
'System.Windows.Documents.FixedPage',
'System.Windows.Documents.Floater',
'System.Windows.Documents.FlowDocument',
'System.Windows.Documents.Glyphs',
'System.Windows.Documents.Hyperlink',
'System.Windows.Documents.InlineUIContainer',
'System.Windows.Documents.Italic',
'System.Windows.Documents.LineBreak',
'System.Windows.Documents.LinkTarget',
'System.Windows.Documents.LinkTargetCollection',
'System.Windows.Documents.List',
'System.Windows.Documents.ListItem',
'System.Windows.Documents.PageContent',
'System.Windows.Documents.Paragraph',
'System.Windows.Documents.Run',
'System.Windows.Documents.Section',
'System.Windows.Documents.Span',
'System.Windows.Documents.Table',
'System.Windows.Documents.TableCell',
'System.Windows.Documents.TableColumn',
'System.Windows.Documents.TableRow',
'System.Windows.Documents.TableRowGroup',
'System.Windows.Documents.TextElementEditingBehaviorAttribute',
'System.Windows.Documents.Underline',
'System.Windows.Documents.ZoomPercentageConverter',
'System.Windows.Input.CommandConverter',
'System.Windows.Interop.DocObjHost',
'System.Windows.Markup.Localizer.BamlLocalizableResource',
'System.Windows.Markup.Localizer.BamlLocalizationDictionary',
'System.Windows.Markup.Localizer.ElementLocalizability',
'System.Windows.Markup.ArrayExtension',
'System.Windows.Markup.ComponentResourceKeyConverter',
'System.Windows.Markup.DependencyPropertyConverter',
'System.Windows.Markup.NamespaceMapEntry',
'System.Windows.Markup.NullExtension',
'System.Windows.Markup.ParserContext',
'System.Windows.Markup.ResourceReferenceExpressionConverter',
'System.Windows.Markup.RoutedEventConverter',
'System.Windows.Markup.StaticExtension',
'System.Windows.Markup.TemplateKeyConverter',
'System.Windows.Markup.TypeExtension',
'System.Windows.Markup.XamlParseException',
'System.Windows.Markup.XamlReader',
'System.Windows.Media.Animation.BeginStoryboard',
'System.Windows.Media.Animation.DiscreteThicknessKeyFrame',
'System.Windows.Media.Animation.LinearThicknessKeyFrame',
'System.Windows.Media.Animation.PauseStoryboard',
'System.Windows.Media.Animation.RemoveStoryboard',
'System.Windows.Media.Animation.ResumeStoryboard',
'System.Windows.Media.Animation.SeekStoryboard',
'System.Windows.Media.Animation.SetStoryboardSpeedRatio',
'System.Windows.Media.Animation.SkipStoryboardToFill',
'System.Windows.Media.Animation.SplineThicknessKeyFrame',
'System.Windows.Media.Animation.StopStoryboard',
'System.Windows.Media.Animation.Storyboard',
'System.Windows.Media.Animation.ThicknessAnimation',
'System.Windows.Media.Animation.ThicknessAnimationUsingKeyFrames',
'System.Windows.Media.Animation.ThicknessKeyFrameCollection',
'System.Windows.Media.Effects.BevelBitmapEffect',
'System.Windows.Media.Effects.BitmapEffectGroup',
'System.Windows.Media.Effects.BlurBitmapEffect',
'System.Windows.Media.Effects.DropShadowBitmapEffect',
'System.Windows.Media.Effects.EmbossBitmapEffect',
'System.Windows.Media.Effects.OuterGlowBitmapEffect',
'System.Windows.Media.LinearGradientBrush',
'System.Windows.Media.RadialGradientBrush',
'System.Windows.Media.GradientStop',
'System.Windows.Media.ImageBrush',
'System.Windows.Media.ImageDrawing',
'System.Windows.Media.MediaPlayer',
'System.Windows.Media.VideoDrawing',
'System.Windows.Media.VisualBrush',
'System.Windows.Media.MatrixTransform',
'System.Windows.Media.RotateTransform',
'System.Windows.Media.ScaleTransform',
'System.Windows.Media.SkewTransform',
'System.Windows.Media.TransformGroup',
'System.Windows.Media.TranslateTransform',
'System.Windows.Navigation.JournalEntryListConverter',
'System.Windows.Navigation.JournalEntryUnifiedViewConverter',
'System.Windows.Navigation.NavigationWindow',
'System.Windows.AttachedPropertyBrowsableForChildrenAttribute',
'System.Windows.ColorConvertedBitmapExtension',
'System.Windows.ComponentResourceKey',
'System.Windows.Condition',
'System.Windows.ConditionCollection',
'System.Windows.CornerRadiusConverter',
'System.Windows.DataTemplate',
'System.Windows.DataTemplateKey',
'System.Windows.DataTrigger',
'System.Windows.DialogResultConverter',
'System.Windows.DynamicResourceExtension',
'System.Windows.DynamicResourceExtensionConverter',
'System.Windows.EventSetter',
'System.Windows.EventTrigger',
'System.Windows.FigureLengthConverter',
'System.Windows.FontSizeConverter',
'System.Windows.FrameworkContentElement',
'System.Windows.FrameworkElement',
'System.Windows.FrameworkElementFactory',
'System.Windows.FrameworkPropertyMetadata',
'System.Windows.GridLengthConverter',
'System.Windows.HierarchicalDataTemplate',
'System.Windows.LengthConverter',
'System.Windows.MultiDataTrigger',
'System.Windows.MultiTrigger',
'System.Windows.NameScope',
'System.Windows.NullableBoolConverter',
'System.Windows.PropertyPathConverter',
'System.Windows.ResourceDictionary',
'System.Windows.ResourceReferenceKeyNotFoundException',
'System.Windows.Setter',
'System.Windows.SetterBaseCollection',
'System.Windows.StaticResourceExtension',
'System.Windows.Style',
'System.Windows.StyleTypedPropertyAttribute',
'System.Windows.TemplateBindingExpressionConverter',
'System.Windows.TemplateBindingExtension',
'System.Windows.TemplateBindingExtensionConverter',
'System.Windows.TemplatePartAttribute',
'System.Windows.ThemeDictionaryExtension',
'System.Windows.ThicknessConverter',
'System.Windows.Trigger',
'System.Windows.TriggerActionCollection',
'System.Windows.Window',
'System.Windows.WindowCollection',
'System.Windows.Resources.ContentTypes',
'System.Windows.Resources.StreamResourceInfo',
'System.Windows.Shapes.Ellipse',
'System.Windows.Shapes.Line',
'System.Windows.Shapes.Path',
'System.Windows.Shapes.Polygon',
'System.Windows.Shapes.Polyline',
'System.Windows.Shapes.Rectangle'

# SIG # Begin signature block
# MIILCQYJKoZIhvcNAQcCoIIK+jCCCvYCAQExCzAJBgUrDgMCGgUAMGkGCisGAQQB
# gjcCAQSgWzBZMDQGCisGAQQBgjcCAR4wJgIDAQAABBAfzDtgWUsITrck0sYpfvNR
# AgEAAgEAAgEAAgEAAgEAMCEwCQYFKw4DAhoFAAQUY9ZSWifp2YsPyrs9PgjqRJ1i
# 6uegggbgMIIG3DCCBMSgAwIBAgIJALPpqDj9wp7xMA0GCSqGSIb3DQEBBQUAMIHj
# MQswCQYDVQQGEwJVUzERMA8GA1UECBMITmV3IFlvcmsxEjAQBgNVBAcTCVJvY2hl
# c3RlcjEhMB8GA1UEChMYaHR0cDovL0h1ZGRsZWRNYXNzZXMub3JnMSgwJgYDVQQL
# Ex9TY3JpcHRpbmcgQ2VydGlmaWNhdGUgQXV0aG9yaXR5MTcwNQYDVQQDEy5odHRw
# Oi8vSHVkZGxlZE1hc3Nlcy5vcmcgQ2VydGlmaWNhdGUgQXV0aG9yaXR5MScwJQYJ
# KoZIhvcNAQkBFhhKYXlrdWxASHVkZGxlZE1hc3Nlcy5vcmcwHhcNMDkwMzE1MTkx
# OTE5WhcNMTAwMzE1MTkxOTE5WjCBqzELMAkGA1UEBhMCVVMxETAPBgNVBAgTCE5l
# dyBZb3JrMRIwEAYDVQQHEwlSb2NoZXN0ZXIxITAfBgNVBAoTGGh0dHA6Ly9IdWRk
# bGVkTWFzc2VzLm9yZzESMBAGA1UECxMJU2NyaXB0aW5nMRUwEwYDVQQDEwxKb2Vs
# IEJlbm5ldHQxJzAlBgkqhkiG9w0BCQEWGEpheWt1bEBIdWRkbGVkTWFzc2VzLm9y
# ZzCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBAPfqxOG9TQN+qZjZ6KfM
# +zBK0YpjeyPL/cFgiGBhiIdYWTBtkbZydFr3IiERKRsUJ0/SKFbhf0C3Bvd/neTJ
# qiZjH4D6xkrfdLlWMmmSXXqjSt48jZp+zfCAIaF8K84e9//7lMicdVFE6VcgoATZ
# /eMKQky4JvphJpzDHYPLxLJQrKd0pjDDwspjdX5RedWkzeZBG7VfBnebLWUzgnMX
# IxRQKfFCMryQDP8weceOnJjfJEf2FYmdpsEg5EKKKbuHsQCMVTxfteKdPvh1oh05
# 1GWyPsvEPh4auJUT8pAVvrdxq+/O9KW/UV01UxjRYM1vdklNw8g7mkJTrrHjSjl7
# tuugCnJjt5kN6v/OaUtRRMR68O85bSTVGOxJGCHUKlyuuTx9tnfIgy4siFYX1Ve8
# xwaAdN3haTon3UkWzncHOq3reCIVF0luwRZu7u+TnOAnz2BRlt+rcT0O73GN20Fx
# gyN2f5VGBbw1KuS7T8XZ0TFCspUdgwAcmTGuEVJKGhVcGAvNlLx+KPc5dba4qEfs
# VZ0MssC2rALC1z61qWuucb5psHYhuD2tw1SrztywuxihIirZD+1+yKE4LsjkM1zG
# fQwDO/DQJwkdByjfB2I64p6mk36OlZAFxVfRBpXSCzdzbgKpuPsbtjkb5lGvKjE1
# JFVls1SHLJ9q80jHz6yW7juBAgMBAAGjgcgwgcUwHQYDVR0OBBYEFO0wLZyg+qGH
# Z4WO8ucEGNIdU1T9MB8GA1UdIwQYMBaAFN2N42ZweJLF1mz0j70TMxePMcUHMAkG
# A1UdEwQCMAAwEQYJYIZIAYb4QgEBBAQDAgTwMCoGA1UdJQEB/wQgMB4GCCsGAQUF
# BwMBBggrBgEFBQcDAgYIKwYBBQUHAwMwCwYDVR0PBAQDAgTwMCwGCWCGSAGG+EIB
# DQQfFh1PcGVuU1NMIEdlbmVyYXRlZCBDZXJ0aWZpY2F0ZTANBgkqhkiG9w0BAQUF
# AAOCAgEAmKihxd6KYamLG0YLvs/unUTVJ+NW3jZP16R28PpmidY/kaBFOPhYyMl2
# bBGQABe7LA5rpHFAs0F56gYETNoFk0qREVvaoz9u18VfLb0Uwqtnq0P68L4c7p2q
# V3nKmWjeI6H7BAyFuogxmMH5TGDfiqrrVSuh1LtPbkV2Wtto0SAxP0Ndyts2J8Ha
# vu/2rt0Ic5AkyD+RblFPtzkCC/MLVwSNAiDSKGRPRrLaiGxntEzR59GRyf2vwhGg
# oAXUqcJ/CVeHCP6qdSTM39Ut3RmMZHXz5qY8bvLgNYL6MtcJAx+EeUhW497alzm1
# jInXdbikIh0d/peTSDyLbjS8CPFFtS6Z56TDGMf+ouTpEA16otcWIPA8Zfjq+7n7
# iBHjeuy7ONoJ2VDNgqn9B+ft8UWRwnJbyB85T83OAGf4vyhCPz3Kg8kWxY30Bhnp
# Fayc6zQKCpn5o5T0/a0BBHwAyMfr7Lhav+61GpzzG1KfAw58N2GV8KCPKNEd3Zdz
# y07aJadroVkW5R+35mSafKRJp5pz20GDRwZQllqGH1Y/UJFEiI0Bme9ecbl2vzNp
# JjHyl/jLVzNVrBI5Zwb0lCLsykApgNY0yrwEqaiqwcxq5nkXFDhDPQvbdulihSo0
# u33fJreCm2fFyGbTuvR61goSksAvLQhvijLAzcKqWKG+laOtYpAxggOTMIIDjwIB
# ATCB8TCB4zELMAkGA1UEBhMCVVMxETAPBgNVBAgTCE5ldyBZb3JrMRIwEAYDVQQH
# EwlSb2NoZXN0ZXIxITAfBgNVBAoTGGh0dHA6Ly9IdWRkbGVkTWFzc2VzLm9yZzEo
# MCYGA1UECxMfU2NyaXB0aW5nIENlcnRpZmljYXRlIEF1dGhvcml0eTE3MDUGA1UE
# AxMuaHR0cDovL0h1ZGRsZWRNYXNzZXMub3JnIENlcnRpZmljYXRlIEF1dGhvcml0
# eTEnMCUGCSqGSIb3DQEJARYYSmF5a3VsQEh1ZGRsZWRNYXNzZXMub3JnAgkAs+mo
# OP3CnvEwCQYFKw4DAhoFAKB4MBgGCisGAQQBgjcCAQwxCjAIoAKAAKECgAAwGQYJ
# KoZIhvcNAQkDMQwGCisGAQQBgjcCAQQwHAYKKwYBBAGCNwIBCzEOMAwGCisGAQQB
# gjcCARUwIwYJKoZIhvcNAQkEMRYEFGF8j1l/VKToh8YL7fV2Zhf2Ef15MA0GCSqG
# SIb3DQEBAQUABIICAOGGaOLut26ENcKTMV9nX4VcGbBggV4qT2FtQYkt1J3EGsYj
# WowkBOcCnR6sYDWbKFLsSJW4t9MjE1xhi6+Uk9l6T8bQHGvT8Ngt30gRSvTLm2Hj
# 8nTQcL5YGQuDD+DUOeGvtW7xts1MKX00RntM6y/GaQDfaa3Hn77e8Qt2UoJoeGde
# al5Oihpw1Y3XvbJcKQcpZZ3yWwNif5CUGT/88WgO+HAUHLaEIeHuvvfknjiomNlA
# jmwEXm8iys0hwG0NDyXbVrwWYTTJmXtr+Ipe+5VbcDP0xUY9hONqP/ihd5ZrNAR4
# Ki0atPokZI+MU1/kVm6l1GJ9rGmfxyr4Ku41wepcQTziSjV/qVRUuf0kTwPRyhlD
# mWgnzstifuaOywskqUWZbQnXs6gH2WHew3HWNFefKiJ5P5Fb/23V4QIZ8rFE+3hj
# mQyS9NIn+cIGfiSjAbTzxYxsl1HwhTPZQW/aJ3C3vv4LLlySjCMQfVnaLi+DNL1W
# B5ip0nDun2xnIl4481NJTfdS6fbpxgHm/3qOw4FZ0YK2hWUal5FRbAOiOUDL3UpM
# PWZmxDy7nNF/Ah10z8iBXnpu5BjtecBRAAEA6PTwnC8nmP+ue9riDE9qVJqJMGMH
# 55eVJ5tAp5xu7QaMzGpwsEB9SkV0l1Qd/q8qYsZpwhLoWya2jBRMNgyhoyuS
# SIG # End signature block
